### PR TITLE
Specify Flags for `./mach` bootstrap in `trunk.sh`

### PR DESCRIPTION
**Pull request by wagesj45**
Since we're building without artifacts enabled, we can pass `--application-choice "Firefox for Desktop"` into `./mach bootstrap`.

To support automation, we can pass `--no-system-chances` into `./mach bootstrap` to avoid the mercurial setup wizard.

### CODE REVIEW

**Review by gz83 — CHANGES_REQUESTED** [review]
It is not recommended to modify the command directly. You can use other parameters instead and put your command under this parameter.

In addition, I will only do the initial review and the final opinion needs to be made by Alex

**Comment by wagesj45** [comment]
I'm sorry I'm not sure I understand your meaning. Do you mean that `trunk.sh` should be modified to to accept these parameters and pass *those* into `./mach`? I'm not sure how else to run the `bootstrap` command in `./mach` without requiring interactivity.

**Example**
`./trunk.sh --no-interaction`
...
```bash
...
if [[ " $* " =~ " --no-interaction " ]]; then
    ./mach bootstrap --application-choice "Firefox for Desktop" --no-system-changes
else
    ./mach bootstrap
fi &&
...
```

**Comment by gz83** [comment]
You have understood my previous comment, but please also test thoroughly before modifying this PR.

@wagesj45

**Comment by wagesj45** [comment]
I have explained my changes here. I chose not to put them behind a passed parameter because the single `--application-choice` value is in line with the official documentation. This is just doing what the `HG_SETUP.md` documentation already mandates.

**Pull request closed without merging**
